### ISSUE TITLE
Trudniejsze pytanie, za które mozna najwięcej zyskać ;)

### ISSUE THREAD

**Issue by this-jaku** [stasiu20/gambit#13]
Załóżmy, że w systemie mam poniższy układ klas i kawałek implementacji.

![image](https://user-images.githubusercontent.com/10431756/166238023-82dd0545-113c-4f8f-a734-122bab69c400.png)

Zadanie 1:
Chciałbym, żeby metoda findById zwracała jedną z dwóch klas, zależnie od wartości `market_type`
There are 2 kinds of predictions:
● 3 way result (1 - Home team win, X - Draw, 2 - Away team win)
● correct score (e.g. 3:2, 1:0, 5:3)

Jak można wykorzystać do tego wzorzec Factory? (propozycja w pseudokodzie)
Gdzie umieścić tego typu Factory? (propozycja w pseudokodzie)

Zadanie 2:
Gdybym miał już instancję jednej z dwóch klas Prediction, a następnie chciał zmodyfikować jej status i zapisać taką zmianę w bazie.
Jak może wyglądać taka implementacja*? Czy należy dodać jakieś klasy np. Service, lub dodać metody w istniejących klasach? 

 *pseudokod, lub dopiski a'la Paint do powyższego obrazka

**Comment by stasiu20** [comment]
Zadanie pierwsze: 

Stworzył bym dwie klasy 

- Prediction3WayResult
- PredictionCorrectScore
Oraz zaimplementowałbym w obu PredictionInterface
wtedy zmodyfikował bym findById i dodał bym warunek if, w tym przypadku wystarczy, jeśli było by więcej klas Prediction, wtedy zastosował bym switch
```
function findById(string $id): PredictionInterface
{
  $query = 'SELECT * FROM prediction WHERE id = :id';
  $predictionRow = $sqlQuery->prepare($query)
  ->bind('id', $id)
  ->execute($query);
  
 if($predictionRow['market_type'] == 'correct_score') {
     $prediction = new PredictionCorrectScore();
 } else {
     $prediction = new Prediction3WayResult();
 }
 return $prediction;
}
```

zadanie 2: 

Nasze dwie klasy Prediction implementują PredictionInterface więc muszą nadpisać metodę changeStatus(status) z tego interface.
