### ISSUE TITLE
tworzenie aktualizacja schemy

### ISSUE THREAD

**Issue by this-jaku** [stasiu20/gambit#5]
Do projektu dołączony jest plik `gambit.sql`, który trzeba zaimportować ręcznie.
Jakie znasz sposoby na utrzymanie schemy bazy danych?
Czy w jaki sposób (metodyka, narzędzia) może być aktualizowana baza danych na produkcyjnym projekcie?

**Comment by stasiu20** [comment]
Dobrym rozwiązaniem jest użycie Workbencha

**Comment by this-jaku** [comment]
a czy znasz jakieś mechanizmy/biblioteki na poziomie aplikacji, które można by zapiąć w CI/CD?

**Comment by stasiu20** [comment]
znalazłem bibliotekę doctrine-migrations którą można użyć w projekcie i odpalać z poziomu Vagranta
