### ISSUE TITLE
nadamiarowy kod

### ISSUE THREAD

**Issue by this-jaku** [stasiu20/gambit#6]
Które fragmenty kodu są Twoim zdaniem nadmiarowe i mogą zostać usunięte?

**Comment by stasiu20** [comment]
Oprócz rzeczy które są dostarczane przez framework jako baseline, to widoki są nie potrzebne skoro jest to Rest Api

**Comment by this-jaku** [comment]
co z klasami związanymi np. z User?

**Comment by stasiu20** [comment]
W zasadzie wszystkie kontrolery i widoki dostarczone przez framework mogą zostać usunięte.
