### ISSUE TITLE
PUT 422

### ISSUE THREAD

**Issue by this-jaku** [stasiu20/gambit#7]
Wysyłając `PUT /v1/prediction/7/status`
```
{
    "status": "sratus"
}
```
otrzymałem `422 Data Validation Failed`
Czy to poprawny kod?
Jeśli tak, to dlaczego?
Jeśli nie, to jaki powinien być, oraz co trzeba zmienić w kodzie, żeby zwrócony został inny kod?

**Comment by stasiu20** [comment]
Pewnie nie :), ale moim zdaniem jest odpowiedni, skoro status nie jest poprawny

**Comment by this-jaku** [comment]
a jeśli powiem że mam na to kwity w treści zadania? ;)

**Comment by stasiu20** [comment]
Racja w zadaniu jest mowa o 400, jednakże w normalnej sytuacji starał bym się Ciebie przekonać iż kod 422 wcale nie jest gorszy, a wręcz przeciwnie, bardziej odpowiada na błędnie przesłane żądanie ;)
