### ISSUE TITLE
the future is now!

### ISSUE THREAD

**Issue by this-jaku** [stasiu20/gambit#8]
Mogę dodać predykcje na przyszłość ;)
```
POST /v1/prediction

{
    "event_id": 3,
    "market_type": "correct_score",
    "prediction": "3:2",
    "status": "win",
    "created_at": "2032-05-02 11:10:57"
}
```
Co powinno być walidowane na tym żądaniu?

**Comment by stasiu20** [comment]
Fakt data created_at powinna być aktualną datą, więc najlepiej jakby była pomijana w requescie i wpisana bezpośrednio przez bazę i tak jest zapisywana tylko raz, nie zmienia się przy update :) i nie trzeba by jej dodatkowo walidować

**Comment by this-jaku** [comment]
podsumowując, co i jak powinno być walidowane na tym request?
